### ISSUE TITLE
Build ToDo App PLAN

### ISSUE THREAD

**Issue by genadikupreishvili** [genadikupreishvili/todo-app-py#1]
- [ ] Setup a Frontend Development Environment
- [ ] Set up Beckend Development Environment
- [ ] Created a ToDo App item list on the frontend using HTML and CSS.
- [ ] Add ToDo App component and item to the list.
- [ ] Build Todo  item edit feature on frontend
- [ ] Build django API  endpointto get list of ToDo items
- [ ] Build django API endpoint to edit single item
